### ISSUE TITLE
Using this script for copying symlinks in vb

### ISSUE THREAD

**Issue by PromGames** [francisrohner/CopyCat#1]
Hi, good job done with your script..

More and more, symlinks are used in Windows environment and I think your tool will be able to deal with symlinks. Normally, when you copy a directory that include symlinks, Windows will copy the linked file and not the link itself.

Using xcopy with the SL parameter could maybe solve the problem and keep the symlinks in the new directory. I have to check but could be a good enhancement for your code.

Detect symlinks files is easy as they have some flags. If xcopy is not able to deal with symlinks, other system that works fine is robocopy, standard also in win10

**Comment by francisrohner** [comment]
Thank you @PromGames, I'll see If I can work in symlink copy.

**Comment by francisrohner** [comment]
3 years late... but I did a brief test and it appears to copy symlinks correctly.
